<?php
/**
 * @File
 */

/**
 * Implements hook_init().
 */
function tweaks_init() {
}

/**
 * Implements hook_form_alter().
 */
function tweaks_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'search_block_form') {
    $form['search_block_form']['#size'] = 30;
  }

}



function tweaks_block_info() {
  $blocks['taxonomy_menu'] = array(
    'info' => t('Taxonomy menu'),
  );

  return $blocks;
}

function tweaks_block_view($delta = '') {
  $block = array();
  // Taxonomy menu block.
  if ($delta == 'taxonomy_menu') {
    $vocabulary = taxonomy_vocabulary_machine_name_load('beverage');
    $terms = taxonomy_get_tree($vocabulary->vid); // Use the correct vocabulary id.
    
    // Get the active trail tid-s.
    $active = arg(2);
    $active_parents = taxonomy_get_parents_all($active);
    $active_parents_tids = array();
    foreach ($active_parents as $parent) {
      $active_parents_tids[] = $parent->tid;
    }
    
    // Build the menu.
    $term_count = count($terms);
    $cont = '<nav class="navbar navbar-default" role="navigation">
	  <!-- Brand and toggle get grouped for better mobile display -->
	  <div class="navbar-header">
	    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
	      <span class="sr-only">Toggle navigation</span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	    </button>
	    <a class="navbar-brand" href="#">Brand</a>
	  </div>	
	  <!-- Collect the nav links, forms, and other content for toggling -->
	  <div class="collapse navbar-collapse navbar-ex1-collapse">
	    <ul class="nav navbar-nav">';

    
    for ($i = 0; $i < $term_count; $i++) {
      // Build the classes string.
      $classes = '';
      $children = taxonomy_get_children($terms[$i]->tid);
      $active_trail = in_array($terms[$i]->tid, $active_parents_tids);
      $glyphicon = 'glyphicon-minus';
      if ($active_trail && $children) {
        $classes .= 'expanded active-trail ';
        $glyphicon = 'glyphicon-plus';
      }
      elseif ($active_trail) { 
        $classes .= 'active-trail ';
        $glyphicon = 'glyphicon-plus';
      }
      elseif ($children) {
        $classes .= 'collapsed ';
        $glyphicon = 'glyphicon-plus';
      } 
             
      if ($i == 0) { 
        /*$cont .= '<li class="dropdown active">'.
      l($terms[$i]->name .'<b class="caret"></b>', 'taxonomy/term/'.$terms[$i]->tid, 
      array('html' => true, 'attributes' => array('class' => 'dropdown-toggle', 'data-toggle' => 'dropdown')));*/
      }
      else {
      
        if ($terms[$i]->depth == $depth) { 
          /*$cont .= '</li><li class="'.$classes.'">'.
        	l('<i class="glyphicon glyphicon-minus" aria-hidden="true"></i>'.$terms[$i]->name, 'taxonomy/term/'.$terms[$i]->tid, array('html' => true));*/
        	
        	$cont .= '</li><li class="'.$classes.' level-'.$terms[$i]->depth.'">'. l($terms[$i]->name, 'taxonomy/term/'.$terms[$i]->tid, array('html' => true));
        	
        } elseif ($terms[$i]->depth > $depth) {
	        /*$cont .= '<ul class="level-'.$terms[$i]->depth.' nav nav-list tree">
			<li class="first '.$classes.' tree-toggle nav-header">'.
			l('<i class="glyphicon '. $glyphicon .'" aria-hidden="true"></i>'. $terms[$i]->name, 'taxonomy/term/'.$terms[$i]->tid, array('html' => true));*/
           
			$cont .= '<ul class="dropdown-menu">'.
            '<li class="level-'.$terms[$i]->depth.'">'. l($terms[$i]->name, 'taxonomy/term/'.$terms[$i]->tid, array('html' => true));
			         
			
        } elseif ($terms[$i]->depth < $depth) {
          // Add missing end-tags depending of depth level difference.
          for ($j = $terms[$i]->depth; $j < $depth; $j++) {
            $cont .= '</li></ul>';
          }
          /*$cont .= '</li><li class="'.$classes.'">'. l('<i class="glyphicon glyphicon-plus" aria-hidden="true"></i>'. $terms[$i]->name, 'taxonomy/term/'.$terms[$i]->tid, array('html' => true));*/
          
          $cont .= '</li><li class="'.$classes.' level-'.$terms[$i]->depth.'">'. l($terms[$i]->name, 'taxonomy/term/'.$terms[$i]->tid, array('html' => true));
        }
        // If we have reached the last element add all possibly missing end-tags.
        if (!isset($terms[$i+1])) {
          for ($j = 0; $j < $terms[$i]->depth; $j++) {
            $cont .= '</li></ul>';
          }
        }
      }
      $depth = $terms[$i]->depth;
    }
    $cont .= '</li></ul>';
$cont .= '</div></nav>';
    
    // Set the menu html as block content.
    $block['content'] = array('#markup' => $cont);
  }
  
  return $block;
}

/*
function tweaks_block_view($delta = '') {
  $block = array();
  // Taxonomy menu block.
   if ($delta == 'taxonomy_menu') {
      $block['content'] = '
		      <nav class="navbar navbar-default" role="navigation">
			  <!-- Brand and toggle get grouped for better mobile display -->
			  <div class="navbar-header">
			    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
			      <span class="sr-only">Toggle navigation</span>
			      <span class="icon-bar"></span>
			      <span class="icon-bar"></span>
			      <span class="icon-bar"></span>
			    </button>
			    <a class="navbar-brand" href="#">Brand</a>
			  </div>
			
			  <!-- Collect the nav links, forms, and other content for toggling -->
			  <div class="collapse navbar-collapse navbar-ex1-collapse">
			    <ul class="nav navbar-nav">
			      <li class="dropdown active"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a></li>
			      <li><a href="#">Link</a></li>
			      <li class="dropdown">
			        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
			        <ul class="dropdown-menu">
			          <li><a href="#">Action</a></li>
			          <li><a href="#">Another action</a></li>
			          <li><a href="#">Something else here</a></li>
			          <li><a href="#">Separated link</a></li>
			          <li><a href="#">One more separated link</a></li>
			        </ul>
			      </li>
			    </ul>
			 
			  </div><!-- /.navbar-collapse -->
			</nav>';
		    
   }
   return $block;
}
*/
function tweaks_views_post_execute(&$view) {
 //if ($view->name == 'homepage_blocks') {
   foreach ($view->result as $result) {
   
    //if( $result->nid == 1 ){
       $result->node_title = 'something here'; 
      // }
    
   }
 //}
}
  
  
  
